# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: mongo-replica-set
spec:
  selector:
    app: mongo
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-node-0
  namespace: mongo-replica-set
spec:
  selector:
    name: mongo-node-0
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-node-1
  namespace: mongo-replica-set
spec:
  selector:
    name: mongo-node-1
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-node-2
  namespace: mongo-replica-set
spec:
  selector:
    name: mongo-node-2
  ports:
  - name: mongo
    port: 27017
    targetPort: 27017
