# Copyright (c) 2016 Kazumasa Kohtaka. All rights reserved.
# This file is available under the MIT license.

apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: mongo-replica-set
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: prometheus
    port: 9090
    targetPort: 9090
    nodePort: 30090
